# Generated by Django 5.0.2 on 2024-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=255)),
                ('completed', models.DateField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
